language: node_js

node_js:
    - "stable"
    - "8"
    - "6"

cache:
  directories:
    - node_modules

notifications:
    email: false

branches:
  only:
    - master
    - /^v[0-9].*$/

after_success:
  - npm run report-coverage -- -e TRAVIS_NODE_VERSION
