language: node_js

node_js:
    - "stable"
    - "8"
    - "6"

cache:
  yarn: true
  directories:
    - node_modules

notifications:
    email: false

branches:
  only:
    - master
    - /^v[0-9].*$/

after_success:
  - npm run report-coverage -- -e TRAVIS_NODE_VERSION

env:
  global:
    - secure: "lq60AD3qS4f1Td0XPweofeMGxz7/C0bGgKeCRtwvf7BJEI2buYOxeXZKwfNDvnImrPTgobq8CYsLGiTInzS1WclwTvm9YjRVCY2+2V49EAaod95q7BBIJsTG6wePWUW/O+mOseAtghW1C7MefcI5Gpjvu4Fg5C3X1RTW1LKnEo8CeM+1miJtw8Gje0J5WoIwZSX7l0mCto18xW6GH4JfgRAsbwsHiXlybCzwHTKUJbDBXcoBKwWu7UcwNuJxML/MgRXa6Am61z7U3mZq92wAIatyjgySST/LJqtPVJJ0OVe1PATgBya57OUdxOxb9ZNYr8AVC1vfpDBSrFaANawUicmRQWhFO/La7pp+Nsh0NYgJDnS3dj9Q0XExAwSy992svgw2mYtRcTLB3+Pr5f4mxuKKbiQlGT04k8f/7TyM54IaI9oxije6DaotuHLKHp5+KuzqCdk2rcSpf64hT4HbRKpGkdUEI/AQYvjrsYvsek6uoKeNT/GMIEmbEfc6ubVOrcnf3imDTRbFaxrHLkJU6shTF/zy1NcZrqogZWiPw2p+Gg8JuLlNaBrr7omLlQOTmw0rz+WR0FU3UJzbhnsEvXY1bCOokjoBGOpcdCw56RdX4zcfZDE5Uej0BxeYMrSev5XFWh0J9gX/hjCRqYx4NrVkIF6qoZXjn+FUzO53eSA="
    - secure: "RIxLoSb5p7koK12wUAnEh1E0mgWCHe8JB6Pn+w6ONtL+7IqQ8jW5iV28QSR4vlXaN2Bh8KWlOBNQXMSXBr0bgtTbAnHlIyQfi72hEhBiLrbuk8exHVfYI2uSS3n3Ov1kgMfitqJJyCW859BRRKBwI+3b/l0ZOg94hBagwstbbLYSpg072OhakWNzre+TE7ZDyX3WKvaXzWf8AuprAU9HMax1QijMm91lbmts3/nnqFwVTW4w9eTBAKOw7wlYyagQYkY07Oo2vVqWXugX9qhgSZOnv4c1+3Jk9ilBL393oZU5WlGnyGZaKQIWUYN0fy1LctvwkIkUJyuv8i/Ws+Ysy196W7jsda2c7/uiYshM+ebZGUu58mj+zriFHdQsm834Yb3AtOh0O+2oyzKz/0wH394ieIXcsNqS6Zm3EWewMP51IELCbnOfQTb1DIa9VEFP735frAHqFX/XlhYvTEP/lEyH/oAvjaO6TDr18uaR05VT7nnika8m1jlmY9u2ZLN6+Vj85f/HwbuSfcuo2l4JKyZ4i47S6nbAefWbFji7DiEWsg0SuN174nLOF5h4KEztaLKww0/6dD+3MsRpeC+zGOiT+NrcZXxY175PMmakyiXQx+28NPXZ9yu7XjrI/IDZXe//6maASDW9aELc1AReCQFiQZCJrBp85EvMt9l/iPQ="